### ISSUE TITLE
Example dataset can't be accessed through the link provided

### ISSUE THREAD

**Issue by faricazjj** [TF-Chan-Lab/rG4-seeker#3]
Under the _Example dataset_ section of the readme, there is a link provided to _hela-2016-chr20.tar.gz_. However, when I click on this link, it says "Sorry, the file you have requested does not exist."

Is there a different link to the example dataset we can use to run rG4-seeker with?

**Comment by eugenechow** [comment]
Thanks for reporting this issue. The link to the file has been updated.

**Comment by faricazjj** [comment]
@eugenechow thank you for the quick response and fix! I successfully downloaded the example data through the link. 

Closing this issue since it's fixed.
